# Generated by Django 5.0.7 on 2024-07-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subject',
        ),
    ]
